# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

workflows:
  build:
    jobs:
      - build_CM4:
          requires:
              - generate
      - build_CM7:
          requires:
              - generate
      - generate:
          requires:
            - prepare
      - prepare

jobs:
  prepare:
    docker:
      - image: "florianl21/cosmos-build-image:0.0.2"
    steps:
      - run:
          name: Installing pip packages
          command: 'pip3 install jinja2'
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - persist_to_workspace:
        root: .
  generate:
    docker:
      - image: "florianl21/cosmos-build-image:0.0.2"
    environment:
      PYTHONPATH: "/root/project/Cosmos/customBox/generator:/root/project/Cosmos/customBox"
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Generate code from configuration
          command: 'python3 /root/project/Cosmos/customBox/generator/generator.py -w=Cosmos/generated/customBox/configuration/workspace.json'
  build_CM4:
    docker:
      - image: "florianl21/cosmos-build-image:0.0.2"
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Building CM4 image
          command: 'cd /root/project/Cosmos/generated/build/CM4/makefiles && make -j24'
  build_CM7:
    docker:
      - image: "florianl21/cosmos-build-image:0.0.2"
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Building CM7 image
          command: 'cd /root/project/Cosmos/generated/build/CM7/makefiles && make -j24'