version: 2.1

jobs:
  build:
    docker:
      - image: "florianl21/cosmos-build-image:0.0.3"
    environment:
      PYTHONPATH: "/root/project/Cosmos/customBox/generator:/root/project/Cosmos/customBox"
      PYTHON_REQUIREMENTS: "/root/project/Cosmos/customBox/python/requirements.txt"
      CODE_GENERATOR: "/root/project/Cosmos/customBox/python/ConfigurationGenerator.py"
      PYTHON_TEST_RESULTS: "/root/project/Cosmos/generated/python/tests"
      BUILD_OUTPUT_DIR: "/root/project/Cosmos/generated/build"
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: git submodule foreach git checkout master
      - run: git submodule foreach git pull
      - run:
          name: Checkout submodules to the reference project branch, if does not exist master branch is used
          command: 'referenceBranch=$(git branch | sed -n -e "s/^\* \(.*\)/\1/p") && git submodule foreach git pull origin $referenceBranch'
      - restore_cache:
          key: python-requirements-{{ checksum "/root/project/Cosmos/customBox/python/requirements.txt" }}
      - run:
          name: Installing pip packages
          command: 'pip3 install -r /root/project/Cosmos/customBox/python/requirements.txt'
      - save_cache:
          key: python-requirements-{{ checksum "/root/project/Cosmos/customBox/python/requirements.txt" }}
          paths:
            - "/usr/lib/python3.8/site-packages"
      - run:
          name: Building system image with files on master
          command: 'chmod +x /root/project/Cosmos/build/build.sh && cd /root/project/Cosmos/build && ./build.sh --build SYSTEM'
      - run:
          name: Generate code from configuration
          command: 'python3 /root/project/Cosmos/customBox/python/ConfigurationGenerator.py /root/project/Cosmos/configuration/workspace.json'
      - run:
          name: Building system image with newly generated files
          command: 'chmod +x /root/project/Cosmos/build/build.sh && cd /root/project/Cosmos/build && ./build.sh --build SYSTEM'
      - run:
          name: Run C code unit tests
          command: 'chmod +x /root/project/Cosmos/build/build.sh && cd /root/project/Cosmos/build && ./build.sh --build TESTS'
      - run:
          name: Run Python code unit tests
          command: 'cd /root/project && python3 -m pytest'
      - store_test_results:
          path: /root/project/Cosmos/generated/build/tests/tests/results
      - store_test_results:
          path: /root/project/Cosmos/generated/python/tests
      - store_artifacts:
          path: /root/project/Cosmos/generated/python/tests
      - store_artifacts:
          path: /root/project/Cosmos/generated/build/tests/tests/results
      - store_artifacts:
          path: /root/project/Cosmos/generated/build/tests/tests/coverage
      - store_artifacts:
          path: /root/project/Cosmos/generated/build/system/system/CM4.elf
      - store_artifacts:
          path: /root/project/Cosmos/generated/build/system/system/CM4.map
      - store_artifacts:
          path: /root/project/Cosmos/generated/build/system/system/CM7.elf
      - store_artifacts:
          path: /root/project/Cosmos/generated/build/system/system/CM7.map