# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: "ubuntu:latest"
    steps:
      - run:
          name: Installing GCC
          command: 'sudo apt-get update && sudo apt-get install -y gcc-arm-none-eabi'
      - run:
          name: Install needed utilities
          command: 'sudo apt-get install -y make git'
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Building CM4 image
          working_directory: ./reference_project_stmIDE/Cosmos/stm32h755_integration/build/CM4/makefiles
          command: 'make'
      - run:
          name: Building CM7 image
          working_directory: ./reference_project_stmIDE/Cosmos/stm32h755_integration/build/CM7/makefiles
          command: 'make'