version: 2.1

jobs:
  build:
    docker:
      - image: "florianl21/cosmos-build-image:0.0.2"
    environment:
      PYTHONPATH: "/root/project/Cosmos/customBox/generator:/root/project/Cosmos/customBox"
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - restore_cache:
          key: python-requirements-{{ checksum "/root/project/Cosmos/customBox/generator/requirements.txt" }}
      - run:
          name: Installing pip packages
          command: 'pip3 install -r /root/project/Cosmos/customBox/generator/requirements.txt'
      - save_cache:
          key: python-requirements-{{ checksum "/root/project/Cosmos/customBox/generator/requirements.txt" }}
          paths:
            - "/usr/lib/python3.8/site-packages"
      - run:
          name: Building CM4 image with generated files on master
          command: 'cd /root/project/Cosmos/generated/build/CM4/makefiles && make -j24'
      - run:
          name: Building CM7 image with generated files on master
          command: 'cd /root/project/Cosmos/generated/build/CM7/makefiles && make -j24'
      - run:
          name: Generate code from configuration
          command: 'python3 /root/project/Cosmos/customBox/generator/generator.py -w=Cosmos/generated/customBox/configuration/workspace.json'
      - run:
          name: Building CM4 image with newly generated files
          command: 'cd /root/project/Cosmos/generated/build/CM4/makefiles && make -j24'
      - run:
          name: Building CM7 image with newly generated files
          command: 'cd /root/project/Cosmos/generated/build/CM7/makefiles && make -j24'
      - store_artifacts:
          path: /root/project/Cosmos/generated/build/CM4/bin/CM4.elf
      - store_artifacts:
          path: /root/project/Cosmos/generated/build/CM7/bin/CM7.elf