/********************************************************************************
**                                                                             **
**                       GENERATED FILE BY CosmOS CustomBox                    **
**                                                                             **
*********************************************************************************
**                       DOXYGEN DOCUMENTATION INFORMATION                     **
*****************************************************************************//**
** @file default_CM4.c
*********************************************************************************
<!--                           Version Information                            -->
*********************************************************************************
** @version 1.0.0
** @author Generated by CosmOS CustomBox
*********************************************************************************	
<!--                                 Warnings                                 -->
*********************************************************************************
** @warning Modifying user sections comments can lead to removing user code 
**          during generating of the new CosmOS configuration
********************************************************************************/
/********************************************************************************
** DO NOT MODIFY THIS COMMENT ! Include Files        USER SECTION | Start      **
** start_name =default_CM4_includeFiles
********************************************************************************/
#include "stm32h7xx_hal.h"
#include "default_CM4.h"
/********************************************************************************
** stop_name =default_CM4_includeFiles
** DO NOT MODIFY THIS COMMENT ! Include Files        USER SECTION | Stop       **
********************************************************************************/
/********************************************************************************
**                         Function Prototypes | Start                         **
********************************************************************************/
/* Task in the program default_CM4 */
/* Threads in the program default_CM4 */
extern void IdleThread_CM4(void);
/********************************************************************************
**                         Function Prototypes | Stop                          **
********************************************************************************/
/********************************************************************************  
**                           START OF THE SOURCE FILE                          **
********************************************************************************/
__SEC_START(__DEFAULT_CM4_NOINIT_SECTION_START)
// If your compiler does not support pragmas use __DEFAULT_CM4_NOINIT__SECTION
/********************************************************************************
** DO NOT MODIFY THIS COMMENT !                      USER SECTION | Start      **
** start_name =default_CM4_noInit
********************************************************************************/
/********************************************************************************
** stop_name =default_CM4_noInit
** DO NOT MODIFY THIS COMMENT !                      USER SECTION | Stop       **
********************************************************************************/
__SEC_STOP(__DEFAULT_CM4_NOINIT_SECTION_STOP)

__SEC_START(__DEFAULT_CM4_INIT_SECTION_START)
// If your compiler does not support pragmas use __DEFAULT_CM4_INIT_SECTION
/********************************************************************************
** DO NOT MODIFY THIS COMMENT !                      USER SECTION | Start      **
** start_name =default_CM4_init
********************************************************************************/
int __DEFAULT_CM4_INIT_SECTION counter_IdleThread_CM4 = 0;
/********************************************************************************
** stop_name =default_CM4_init
** DO NOT MODIFY THIS COMMENT !                      USER SECTION | Stop       **
********************************************************************************/
__SEC_STOP(__DEFAULT_CM4_INIT_SECTION_STOP)

/********************************************************************************
** Thread ID macro = THREAD_0_PROGRAM_0_CORE_1_ID
** Program ID macro = PROGRAM_0_CORE_1_ID
********************************************************************************/ 
void IdleThread_CM4(void)
{
/********************************************************************************
** DO NOT MODIFY THIS COMMENT !                      USER SECTION | Start      **
** start_name =IdleThread_CM4
********************************************************************************/
if (counter_IdleThread_CM4 > 100)
{
    cosmosApi_deviceIO_togglePin(GPIOA, GPIO_PIN_4);
}
else
{
    counter_IdleThread_CM4++;
}
/********************************************************************************
** stop_name =IdleThread_CM4
** DO NOT MODIFY THIS COMMENT !                      USER SECTION | Stop       **
********************************************************************************/
};
/********************************************************************************
**                           END OF THE SOURCE FILE                            **
********************************************************************************/