/********************************************************************************
**                                                                             **
**                       GENERATED FILE BY CosmOS CustomBox                    **
**                                                                             **
*********************************************************************************
**                       DOXYGEN DOCUMENTATION INFORMATION                     **
*****************************************************************************//**
** @file default_CM7.c
*********************************************************************************
<!--                           Version Information                            -->
*********************************************************************************
** @version 2.0.0
** @author Generated by CosmOS CustomBox
*********************************************************************************
<!--                                 Warnings                                 -->
*********************************************************************************
** @warning Modifying user sections comments can lead to removing user code
**          during generating of the new CosmOS configuration
********************************************************************************/
#include "default_CM7.h"
/********************************************************************************
** DO NOT MODIFY THIS COMMENT ! Include Files        USER SECTION | Start      **
** start_name =default_CM7_includeFiles
********************************************************************************/
#include "stm32h7xx_hal.h"
#include "default_CM7.h"
/********************************************************************************
** stop_name =default_CM7_includeFiles
** DO NOT MODIFY THIS COMMENT ! Include Files        USER SECTION | Stop       **
********************************************************************************/
/********************************************************************************
**                         Function Prototypes | Start                         **
********************************************************************************/
/* Task in the program default_CM7 */

/* Threads in the program default_CM7 */
/********************************************************************************
**                         Function Prototypes | Stop                          **
********************************************************************************/
/********************************************************************************
**                           START OF THE SOURCE FILE                          **
********************************************************************************/
__SEC_START(__DEFAULT_CM7_NOINIT_SECTION_START)
// If your compiler does not support pragmas use __DEFAULT_CM7_NOINIT__SECTION
/********************************************************************************
** DO NOT MODIFY THIS COMMENT !                      USER SECTION | Start      **
** start_name =default_CM7_noInit
********************************************************************************/

/********************************************************************************
** stop_name =default_CM7_noInit
** DO NOT MODIFY THIS COMMENT !                      USER SECTION | Stop       **
********************************************************************************/
__SEC_STOP(__DEFAULT_CM7_NOINIT_SECTION_STOP)

__SEC_START(__DEFAULT_CM7_INIT_SECTION_START)
// If your compiler does not support pragmas use __DEFAULT_CM7_INIT_SECTION
/********************************************************************************
** DO NOT MODIFY THIS COMMENT !                      USER SECTION | Start      **
** start_name =default_CM7_init
********************************************************************************/
int __DEFAULT_CM7_INIT_SECTION counter_IdleThread_CM7 = 0;
float __DEFAULT_CM7_INIT_SECTION floatTest = 0;
/********************************************************************************
** stop_name =default_CM7_init
** DO NOT MODIFY THIS COMMENT !                      USER SECTION | Stop       **
********************************************************************************/
__SEC_STOP(__DEFAULT_CM7_INIT_SECTION_STOP)


/********************************************************************************
**                           END OF THE SOURCE FILE                            **
********************************************************************************/