/********************************************************************************
**                                                                             **
**                       GENERATED FILE BY CosmOS CustomBox                    **
**                                                                             **
*********************************************************************************
**                       DOXYGEN DOCUMENTATION INFORMATION                     **
*****************************************************************************//**
** @file default_CM7.c
*********************************************************************************
<!--                           Version Information                            -->
*********************************************************************************
** @version 1.0.0
** @author Generated by CosmOS CustomBox
*********************************************************************************	
<!--                                 Warnings                                 -->
*********************************************************************************
** @warning Modifying user sections comments can lead to removing user code 
**          during generating of the new CosmOS configuration
********************************************************************************/
/********************************************************************************
** DO NOT MODIFY THIS COMMENT ! Include Files        USER SECTION | Start      **
** start_name =default_CM7_includeFiles
********************************************************************************/
#include "stm32h7xx_hal.h"
#include "default_CM7.h"
/********************************************************************************
** stop_name =default_CM7_includeFiles
** DO NOT MODIFY THIS COMMENT ! Include Files        USER SECTION | Stop       **
********************************************************************************/
/********************************************************************************
**                         Function Prototypes | Start                         **
********************************************************************************/
/* Task in the program default_CM7 */
/* Threads in the program default_CM7 */
extern void IdleThread_CM7(void);
/********************************************************************************
**                         Function Prototypes | Stop                          **
********************************************************************************/
/********************************************************************************  
**                           START OF THE SOURCE FILE                          **
********************************************************************************/
__SEC_START(__DEFAULT_CM7_NOINIT_SECTION_START)
// If your compiler does not support pragmas use __DEFAULT_CM7_NOINIT__SECTION
/********************************************************************************
** DO NOT MODIFY THIS COMMENT !                      USER SECTION | Start      **
** start_name =default_CM7_noInit
********************************************************************************/
/********************************************************************************
** stop_name =default_CM7_noInit
** DO NOT MODIFY THIS COMMENT !                      USER SECTION | Stop       **
********************************************************************************/
__SEC_STOP(__DEFAULT_CM7_NOINIT_SECTION_STOP)

__SEC_START(__DEFAULT_CM7_INIT_SECTION_START)
// If your compiler does not support pragmas use __DEFAULT_CM7_INIT_SECTION
/********************************************************************************
** DO NOT MODIFY THIS COMMENT !                      USER SECTION | Start      **
** start_name =default_CM7_init
********************************************************************************/
int __DEFAULT_CM7_INIT_SECTION counter_IdleThread_CM7 = 0;
float __DEFAULT_CM7_INIT_SECTION floatTest = 0;
/********************************************************************************
** stop_name =default_CM7_init
** DO NOT MODIFY THIS COMMENT !                      USER SECTION | Stop       **
********************************************************************************/
__SEC_STOP(__DEFAULT_CM7_INIT_SECTION_STOP)

/********************************************************************************
** Thread ID macro = THREAD_0_PROGRAM_0_CORE_0_ID
** Program ID macro = PROGRAM_0_CORE_0_ID
********************************************************************************/ 
void IdleThread_CM7(void)
{
/********************************************************************************
** DO NOT MODIFY THIS COMMENT !                      USER SECTION | Start      **
** start_name =IdleThread_CM7
********************************************************************************/
if (counter_IdleThread_CM7 > 100)
{
    cosmosApi_deviceIO_togglePin(GPIOF, GPIO_PIN_11);
}
else
{
    counter_IdleThread_CM7++;
}
__asm volatile ("VMUL.F32 s0, s0, s1"); //testing FPU context switch
/********************************************************************************
** stop_name =IdleThread_CM7
** DO NOT MODIFY THIS COMMENT !                      USER SECTION | Stop       **
********************************************************************************/
};
/********************************************************************************
**                           END OF THE SOURCE FILE                            **
********************************************************************************/