name: Run unit tests

on:
  repository_dispatch:
    types: [trigger_tests]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    container:
      image: florianl21/cosmos-build-image:0.0.3
    env:
      PYTHONPATH: "$GITHUB_WORKSPACE/Cosmos/customBox/python"

    steps:
      - name: Checkout master branches for all submodules
        env:
          SCRIPT_URL: ${{secrets.COSMOS_CHECKOUT_SCRIPT_URL}}
          BRANCH_NAME: ${{ github.event.client_payload.branch }}
        run: |
          pip3 install GitPython
          mkdir /tools
          cd /tools
          wget $SCRIPT_URL
          python3 /tools/try_submodule_checkout.py $GITHUB_WORKSPACE https://github.com/CosmOS-Creators/reference_project_stmIDE.git $BRANCH_NAME
      - name: Installing required pip packages
        run: pip3 install -r $GITHUB_WORKSPACE/Cosmos/customBox/python/requirements.txt
      - name: Run C code unit tests
        run: |
          chmod +x $GITHUB_WORKSPACE/Cosmos/build/build.sh
          cd $GITHUB_WORKSPACE/Cosmos/build
          ./build.sh --build TESTS
      - name: Run Python code unit tests
        run: |
          cd $GITHUB_WORKSPACE
          python3 -m pytest
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            Cosmos/generated/build/tests/tests/results
            Cosmos/generated/python/tests
            Cosmos/generated/python/tests
            Cosmos/generated/build/tests/tests/results
            Cosmos/generated/build/tests/tests/coverage
          retention-days: 10
      - uses: codecov/codecov-action@v2
        with:
          files: Cosmos/generated/python/tests/coverage/coverage.xml
          flags: python
          # name: python unit test coverage
          fail_ci_if_error: true
