name: Build CM4 and CM7 image

on:
  repository_dispatch:
    types: [trigger_build]



jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: florianl21/cosmos-build-image:0.0.3
    env:
      PYTHONPATH: "$GITHUB_WORKSPACE/Cosmos/customBox/python"

    steps:
      - name: Checkout master branches for all submodules
        env:
          SCRIPT_URL: ${{secrets.COSMOS_CHECKOUT_SCRIPT_URL}}
          BRANCH_NAME: ${{ github.event.client_payload.branch }}
        run: |
          pip3 install GitPython
          mkdir /tools
          cd /tools
          wget $SCRIPT_URL
          python3 /tools/try_submodule_checkout.py $GITHUB_WORKSPACE https://github.com/CosmOS-Creators/reference_project_stmIDE.git $BRANCH_NAME
            - name: Installing required pip packages
      - name: Installing required pip packages
        run: pip3 install -r $GITHUB_WORKSPACE/Cosmos/customBox/python/requirements.txt
      - name: Building system image with files on master
        run: 'chmod +x $GITHUB_WORKSPACE/Cosmos/build/build.sh && cd $GITHUB_WORKSPACE/Cosmos/build && ./build.sh --build SYSTEM'
      - name: Generate code from configuration
        run: 'python3 $GITHUB_WORKSPACE/Cosmos/customBox/python/ConfigurationGenerator.py $GITHUB_WORKSPACE/Cosmos/configuration/workspace.json'
      - name: Building system image with generated files
        run: 'chmod +x $GITHUB_WORKSPACE/Cosmos/build/build.sh && cd $GITHUB_WORKSPACE/Cosmos/build && ./build.sh --build SYSTEM'
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: system-images
          path: |
            $GITHUB_WORKSPACE/Cosmos/generated/build/system/system/CM4.elf
            $GITHUB_WORKSPACE/Cosmos/generated/build/system/system/CM4.map
            $GITHUB_WORKSPACE/Cosmos/generated/build/system/system/CM7.elf
            $GITHUB_WORKSPACE/Cosmos/generated/build/system/system/CM7.map
          retention-days: 10
