name: Build documentation

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger documentation build
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/CosmOS-Creators/CosmOS-Creators.github.io/dispatches -d '{"event_type":"build"}'
