name: PR created handler

on:
  pull_request:
    branches: [ master ]

env:
  BRANCH_NAME: ${{github.head_ref}}

jobs:
  trigger_build:
    runs-on: ubuntu-latest

    steps:
      - uses: felixp8/dispatch-and-wait@v0.1.0
        with:
          owner: CosmOS-Creators
          repo: reference_project_stmIDE
          token: ${{secrets.COSMOS_BUILDER_PAT}}
          event_type: trigger_build
          client_payload: '{ "branch": "'"$BRANCH_NAME"'" }'
  trigger_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: felixp8/dispatch-and-wait@v0.1.0
        with:
          owner: CosmOS-Creators
          repo: reference_project_stmIDE
          token: ${{secrets.COSMOS_BUILDER_PAT}}
          event_type: trigger_tests
          client_payload: '{ "branch": "'"$BRANCH_NAME"'" }'
