name: PR created handler

on:
  pull_request:
    branches: [ master ]

env:
  BRANCH_NAME: ${{github.head_ref}}

jobs:
  trigger_build:
    runs-on: ubuntu-latest
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          owner: CosmOS-Creators
          repo: reference_project_stmIDE
          github_token: ${{secrets.COSMOS_BUILDER_PAT}}
          ref: master
          workflow_file_name: development_compile-image.yml
          inputs: >
            { "branch": "'"$BRANCH_NAME"'" }

  trigger_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          owner: CosmOS-Creators
          repo: reference_project_stmIDE
          github_token: ${{secrets.COSMOS_BUILDER_PAT}}
          ref: master
          workflow_file_name: development_run-unit-tests.yml
          inputs: >
            { "branch": "'"$BRANCH_NAME"'" }
