name: PR created handler

on:
  pull_request:
    branches: [ master ]

jobs:
  trigger_build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger the system build
        env:
          PAT_TOKEN: ${{secrets.COSMOS_BUILDER_PAT}}
          BRANCH_NAME: ${{github.head_ref}}
        run: |
          curl -X POST -u "cosmos-helper:$PAT_TOKEN" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/CosmOS-Creators/reference_project_stmIDE/dispatches -d '{"event_type":"trigger_build", "client_payload": { "branch": "'"$BRANCH_NAME"'" }}'
