name: Push to master handler

on:
  push:
    branches: [ master ]

env:
  PAT_TOKEN: ${{secrets.COSMOS_BUILDER_PAT}}
  BRANCH_NAME: master


jobs:
  trigger_build:
    runs-on: ubuntu-latest

    steps:
      - uses: felixp8/dispatch-and-wait@v0.1.0
        with:
          owner: CosmOS-Creators
          repo: reference_project_stmIDE
          token: ${{secrets.COSMOS_BUILDER_PAT}}
          event_type: trigger_build
          client_payload: '{ "branch": "master" }'
          max_time: 1200
  trigger_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: felixp8/dispatch-and-wait@v0.1.0
        with:
          owner: CosmOS-Creators
          repo: reference_project_stmIDE
          token: ${{secrets.COSMOS_BUILDER_PAT}}
          event_type: trigger_tests
          client_payload: '{ "branch": "master" }'
          max_time: 1200
